### ISSUE TITLE
Deployment of container?

### ISSUE THREAD

**Issue by 96312** [digitalinteraction/netlify-cms-github-auth#19]
Hello there, there was no discussions tab so I'm forced to open an issue instead.

Using your container, I want to set up an auth for a self hosted netlifycms application. I'm planning to host the simple website on firebase. My question is, can I "deploy the container" on the same server where the website is being served from? Or should it ideally be hosted elsewhere and only serve it's purpose in facilitating the authorization? 

Thanks, 
Joe.

**Comment by robb-j** [comment]
It shouldn't matter too much where you host this container. If your platform of choice supports routing with path rewrites, then you could deploy it at `example.com/api/auth/`, for instance, then the container will work as long as the paths are rewritten before network traffic gets to the container. If not, you could set it up as `auth.example.com` and you don't have to worry about path rewriting.

I don't have any experience with Firebase I'm afraid, but I hope I helped!

**Comment by 96312** [comment]
Thanks a lot for the suggestions and helpful pointer about rewritten paths. I will go ahead with setting up a subdomain for my little project. Appreciate the help and thanks for the project!
